### ISSUE TITLE
open_file_dialog not working with 5.0.10 update 

### ISSUE THREAD

**Issue by GTI-Dakota** [OpenC3/openc3#160]
in the script runner, open_file_dialog errors out after a file is selected:

NoMethodError : undefined method `filename=' for #<Tempfile:/tmp/target20220927-29-pev3zl>

Are we missing a require? I have required 'openc3' and 'openc3/script'

Thanks,

Dakota

**Comment by ryanmelt** [comment]
If you add:

require 'openc3/core_ext/tempfile'

That will get you going.  You shouldn't have to do that though.  Will fix.

**Comment by GTI-Dakota** [comment]
requiring that file worked. Thanks!
